version: "3.7"
services:
  airflow:
    build: ../../docker
    image: manning-airflow:latest
    ports:
      - "8080:8080"
    environment:
      MOVIELENS_USER: airflow
      MOVIELENS_PASSWORD: airflow
      # Below host assumes service was named 'movielens' and is running in
      # the 'airflow' namespace, listening on port 80.
      MOVIELENS_HOST: http://movielens.airflow.svc.cluster.local:80
    volumes:
      - ./dags/kubernetes:/root/airflow/dags
      - /Users/nowhereman/.kube/config:/root/.kube/config
      - /Users/nowhereman/.kube/config:/tmp/config
